name: Github Actions 

on:
 workflow_dispatch:

jobs:
  first-job:
     runs-on: ubuntu-latest
     steps:
       - name: Hello World
         run: echo "Hello world"
  Info-Job:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Displaying the info
         run: |
              echo "Printing the outputs about the runner"
              ls -la
              whoami
              pwd
              git --version
              tree
  script-execution:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: script execution
        run: bash script.sh
         
       
      
