name: Multi Select Workflow

on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Enter selected options (comma-separated)'
        required: true

jobs:
  Set_Runner:
    runs-on: ubuntu-latest
    steps:
      - name: Set Runner
        id: set-runner
        run: |
          echo "Determining runner based on the branch..."
          if [[ "${GITHUB_REF}" == "prod_eu" ]]; then
            echo "RUNNER_LABEL=ubuntu-latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "prod" ]]
            echo "RUNNER_LABEL=ubuntu-latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "uat" ]]
            echo "RUNNER_LABEL=ubuntu-latest" >> $GITHUB_ENV 
          elif [[ "${GITHUB_REF}" == "uat_eu" ]]
            echo "RUNNER_LABEL=ubuntu-latest" >> $GITHUB_ENV
          else
            echo "Running the workflow from the different branch, hence exiting..."
          fi

      - name: Print Selected Runner
        run: |
          echo "Selected runner is: $RUNNER_LABEL"
      
