name: Multi Select Workflow

on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Enter selected options (comma-separated)'
        required: true

jobs:
  Set_Runner:
     runs-on: ubuntu-latest
     outputs:
       runner: ${{ steps.set-runner.outputs.runner }}

     steps:
      - name: Set Runner Dynamically
        id: set-runner
        run: |
          echo "Started......"
          echo " ${{ GITHUB.REF }} "
          if [[ "${{ GITHUB.REF }}" == "refs/heads/manual-workflow-test" ]]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::df-0"
          elif [[ "${{ GITHUB.REF }}" == "test-1" ]]; then
            echo "runner=df-1" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::ubuntu-latest"
          else
            echo "None of the above matched........"
            exit 1
          fi
      - name: Printing the runner
        run: |
          echo "Printing the runner picked..."
          echo "Runner: ${{ steps.set-runner.outputs.runner }}"

      - name: Print Selected Runner
        run: |
          echo "Selected runner is: $RUNNER_LABEL"

  job1:
     needs: Set_Runner
     runs-on: ${{ needs.Set_Runner.outputs.runner }}
     steps:
          - name: Dynamic Runner
            run: |
              echo "Running on dynamic runner"
