name: Merge PR Workflow

on:
  pull_request:
    branches:
      - prod_eu
      - prod
      - uat
      - uat_eu
    paths:
     - 'config/**'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Target Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Merging the pull request: ${{ github.event.pull_request.number }}"
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr merge $PR_NUMBER --merge --body "Automatically merged by GitHub Actions."
