name: Merge PR Workflow

on:
  pull_request:
    branches:
      - main
      - test
    paths:
     - 'config/**'
jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN provided by GitHub Actions
        run: |
          echo "Merging the pull request..."
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr merge $PR_NUMBER --merge --body "Automatically merged by GitHub Actions."
