name: Testing Dynamic Runner

on:
 workflow_dispatch:
 pull_request:
  branches:
    - main
    - test
  paths:
   - 'config/**'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}

    steps:
      - name: Set Runner Dynamically
        id: set-runner
        run: |
          echo "Started......"
          echo " ${{ github.event.pull_request.base.ref }} "
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::df-0"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "test-1" ]]; then
            echo "runner=df-1" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::ubuntu-latest"
          else
            echo "None of the above matched........"
          fi
      - name: Printing the runner
        run: |
          echo "Printing the runner picked..."
          echo "Runner: ${{ steps.set-runner.outputs.runner }}"


  job2:
      needs:
        - job1
      runs-on: ${{ needs.job1.outputs.runner }}

      steps:
        - name: Print the runner name
          run: |
            echo  "${{ needs.job1.outputs.runner }}"

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Get changed folders
          id: get-changes
          run: |
            echo "Finding changes in the config folder..."
            # Get the list of changed directories in the config folder
            CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- config/ | grep '/' | cut -d '/' -f 1 | sort -u)
            
            # Output the changed directories
            echo "Changed directories: $CHANGED_DIRS"
            
            # Set the output for use in later steps
            echo "changed_dirs=${CHANGED_DIRS}" >> $GITHUB_OUTPUT

        - name: Iterate over changed folders
          run: |
           echo "Iterating over changed directories..."
           for dir in ${{ steps.get-changes.outputs.changed_dirs }}; do
             echo "Changed directory: $dir"
             # You can add further processing here for each changed directory
           done

