name: Testing Dynamic Runner

on:
 workflow_dispatch:
 pull_request:
  branches:
    - main
    - test
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      selected-runner: ${{ steps.set-runner.outputs.runner }}

    steps:
      - name: Set Runner Dynamically
        id: set-runner
        run: |
          echo "Started......"
          echo " ${{ github.event.pull_request.base.ref }} "
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "runner=df-0" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::df-0"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "test-1" ]]; then
            echo "runner=df-1" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::df-1"
          else
            echo "None of the above matched........"
          fi
      - name: Printing the runner
        run: |
          echo "Printing the runner picked..."
          echo "Runner: ${{ steps.set-runner.outputs.runner }}"


  job2:
      needs:
        - job1
      runs-on: ${{ needs.job1.outputs.runner }}

      steps:
        - name: Print the runner name
          run: |
            echo  "${{ needs.job1.outputs.runner }}"
