name: Testing Dynamic Runner

on:
 workflow_dispatch:
 pull_request:
  branches:
    - main
    - test
  paths:
   - 'config/**'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}

    steps:
      - name: Set Runner Dynamically
        id: set-runner
        run: |
          echo "Started......"
          echo " ${{ github.event.pull_request.base.ref }} "
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::df-0"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "test-1" ]]; then
            echo "runner=df-1" >> $GITHUB_OUTPUT
            echo "::set-output name=runner::ubuntu-latest"
          else
            echo "None of the above matched........"
          fi
      - name: Printing the runner
        run: |
          echo "Printing the runner picked..."
          echo "Runner: ${{ steps.set-runner.outputs.runner }}"


  job2:
      needs:
        - job1
      runs-on: ${{ needs.job1.outputs.runner }}

      steps:
        - name: Print the runner name
          run: |
            echo  "${{ needs.job1.outputs.runner }}"

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Fetch all branches
          run: git fetch --all

        - name: Get changed folders in config
          id: get-changes
          run: |
            echo "Finding changed folders in the config directory..."
            # Get the changed directories under config
            CHANGED_DIRS=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} -- config/ | grep '/' | cut -d '/' -f 2 | sort -u)
  
            # Output the changed directories
            if [ -z "$CHANGED_DIRS" ]; then
              echo "No changed directories in the config folder."
            else
              echo "Changed directories: $CHANGED_DIRS"
              # Set output for use in later steps
              echo "changed_dirs=${CHANGED_DIRS}" >> $GITHUB_OUTPUT
            fi

        - name: Iterate over changed folders
          run: |
            echo "Iterating over changed directories..."
            for dir in ${{ steps.get-changes.outputs.changed_dirs }}; do
              echo "Changed top-level folder: $dir"
              # Further processing for each changed directory can be done here
            done
